### ISSUE TITLE
[BUG] - Bot doesn't work when "XP Boost" button is not present in Skills section

### ISSUE THREAD

**Issue by araujoluks** [lucasmonstrox/PyTibia#78]
**Describe the bug**
Nothing works when you join an OT that doesn't have "XP Boost" button on Skills section

**To Reproduce**
1. Try to play on Rubinot
2. Run bot

**Expected behavior**
Bot should work fine - but it doesn't because all the values are read from below the "XP Boost" button, when in reality it should locate "Skills" section which is more generic and is present in any Tibia/OT client

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tibia Version 13

**Comment by lucasmonstrox** [comment]
@araujoluks already commited today. Is commit https://github.com/lucasmonstrox/PyTibia/commit/9cd2632ea626221747544c0a24d271a9997869f6 enough?

**Comment by lucasmonstrox** [comment]
Resolved in https://github.com/lucasmonstrox/PyTibia/commit/9cd2632ea626221747544c0a24d271a9997869f6

**Comment by araujoluks** [comment]
thanks!!
